services:
  - type: web
    name: sqli-lab
    env: php
    buildCommand: ./render/build.sh
    startCommand: ""
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: trknab
          property: host
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: trkn
      - key: DB_NAME
        value: trknab

databases:
  - name: trknab
    databaseName: trknab
    user: root
    password: trkn
