services:
  - type: web
    name: sqli-lab
    env: docker
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: sqli-lab-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: sqli-lab-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: sqli-lab-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: sqli-lab-db
          property: database

databases:
  - name: sqli-lab-db
    databaseName: trknab
    user: root
    plan: free
    region: frankfurt
    ipAllowList: ["0.0.0.0/0"]
    initCommands:
      - source: ./init.sql
