services:
  - type: web
    name: sqli-lab
    env: php
    buildCommand: ./render/build.sh  # Tu peux le supprimer si tu n’as pas besoin de build.sh
    startCommand: ""  # Laisse vide pour PHP Render standard
    plan: free
    envVars:
      - key: DB_HOST
        fromDatabase:
          name: sqli-lab-db
          property: host
      - key: DB_USER
        fromDatabase:
          name: sqli-lab-db
          property: user
      - key: DB_PASS
        fromDatabase:
          name: sqli-lab-db
          property: password
      - key: DB_NAME
        fromDatabase:
          name: sqli-lab-db
          property: database

databases:
  - name: sqli-lab-db
    databaseName: trkn_lab
    user: root
